### ISSUE TITLE
Select from junction table

### ISSUE THREAD

**Issue by plutonio00** [knpuniversity/doctrine-queries#4]
Hello, everybody!
What should I do if I need to make select from junction table?

For example, I develop project and I need to make chats between users. I have two entities: `User` and `Chat`, and many-to-many relation between them (accordingly, I have three tables: `user, chat, chat_user`). I try to get all chats, which user is member, and to get all users from these chats.

I made the following SQL query:

```
SELECT *
FROM chat c
         INNER JOIN chat_user cu ON c.id = cu.chat_id
         INNER JOIN user u ON u.id = cu.user_id
WHERE c.id IN (SELECT chat_id
               FROM chat_user
               WHERE user_id = <idUser>);
```
But I don't know how to translate in DQL subquery `SELECT chat_id FROM chat_user WHERE user_id = <idUser>`, because a haven't additional entity for table chat_user.

And I tried to add entity ChatUser and get data in ChatRepository smt. like this:

 ```
public function getChatsData($idUser)
    {
        $subQuery = $this->getEntityManager()
            ->getRepository(ChatUser::class)
            ->createQueryBuilder('chus')
            ->select('chus.chat')
            ->andWhere('chus.user = :idUser')
            ->setParameter('idUser', $idUser)
        ;

        $qb = $this->createQueryBuilder('c');

        return $qb
            ->innerJoin('c.chatUsers', 'cu')
            ->addSelect('cu')
            ->innerJoin('cu.user', 'u')
            ->addSelect('u')
            ->innerJoin('c.messages', 'm')
            ->addSelect('m')
            ->andWhere('u.id = :idUser')
            ->andWhere($qb->expr()->in(
                'c.id',
                $subQuery->getQuery()->getResult()
            ))
            ->setParameter('idUser', $idUser)
            ->getQuery()
            ->getResult()
            ;
    }
```
but it doesn't work. I get error ` [Semantical Error] line 0, col 12 near 'chat FROM App\Entity\ChatUser': Error: Invalid PathExpression. Must be a StateFieldPathExpression.`

Have Doctrine standard tools for such tasks?

**Comment by bocharsky-bw** [comment]
Hey @plutonio00 ,

The easiest solution would be to call methods directly, like:
```php
$user->getChats(); // Will return all chats for the $user
// or
$chat->getUsers(); // Will return all users in the $chat
```

That's the standard Doctrine way of doing those queries, i.e. let the Doctrine handle those queries for you. See https://symfonycasts.com/screencast/doctrine-relations/many-to-many for more information about it. Are you sure you need to do those queries manually? Any benefits you want to achieve with it?

But if you want a more complex solution, usually it's used to add more useful data to the additional `chat_user` table (not only chat and user ids) - you would need a new entity e.g. `ChatUser`. Then you make a bit different relations: `Chat` relates as many-to-one to `ChatUser` which in turn relates as one-to-many to `User`. Because many-to-many relations is basically just 2 simple one-to-many relations.

I hope this helps!

Cheers!

**Comment by plutonio00** [comment]
> Any benefits you want to achieve with it?
1. But this way I have one more separate query instead of one. Is it better? 
2. Let's say I got that way all users, and I use them in template smt like this:
```
 {% for user in users %}
    ...
 {% endfor %}
```
But in this case, I'll have problem n+1, right?

**Comment by MolloKhan** [comment]
If the relationship between Chat and User is not set as `EXTRA_LAZY`, then, no. Doctrine will make only one query for fetching all users related to such Chat record

**Comment by bocharsky-bw** [comment]
It depends, you can use a profiler tool, e.g. like Blackfire or Symfony Web Debug Toolbar to profile that page and see how many and which exactly queries are executed

**Comment by plutonio00** [comment]
I did differently, I used ResultSetMapping thus:
```
public function getChatsData(int $userId)
    {
        $em = $this->getEntityManager();
        $rsm = new ResultSetMappingBuilder($em);
        $rsm->addRootEntityFromClassMetadata(
            Chat::class,
            'c',
            [
                'id' => 'c_id',
                'title' => 'c_title',
            ]
        );
        $rsm->addJoinedEntityFromClassMetadata(
            Message::class,
            'm',
            'c',
            'messages',
            [
                'id' => 'm_id',
                'sender_id' => 'm_sender_id',
                'content' => 'm_content',
                'chat_id' => 'm_chat_id',
                'created_at' => 'm_created_at',
                'updated_at' => 'm_updated_at',
            ]
        );
        $rsm->addJoinedEntityFromClassMetadata(
            User::class,
            'u',
            'c',
            'users',
            [
                'id' => 'u_id',
                'avatar' => 'u_avatar',
                'first_name' => 'u_first_name',
                'last_name' => 'u_last_name',
                'created_at' => 'u_created_at',
                'updated_at' => 'u_updated_at',
            ]
        );

        $selectClause = $rsm->generateSelectClause();

        $sql =
            'select ' . $selectClause .
            ' from chat c
                inner join chat_user cu on c.id = cu.chat_id
                inner join message m on m.chat_id = cu.chat_id
                inner join user u on cu.user_id = u.id
            where cu.chat_id in
                (select chat_id from chat_user where user_id = ?)
                and m.created_at in
                (select max(created_at) from message group by chat_id)
            order by m.created_at desc;';

        $query = $em->createNativeQuery($sql, $rsm);
        $query->setParameter(1, $userId);

        return $query->getResult();
    }
```

**Comment by plutonio00** [comment]
So, I got one query, as I wanted, and I got objects as result

**Comment by bocharsky-bw** [comment]
Woh, it does look like a complex solution, glad you figured it out! And thanks for sharing this with others! I'm closing this issue then
